// Curated playlists for SongIQ
// Each playlist uses search terms to fetch tracks from Apple Music/iTunes
export type PlaylistCategory = "africa" | "rap" | "rnb" | "pop" | "gospel";
export interface PlaylistCategoryOption {
  id: "all" | PlaylistCategory;
  label: string;
}
export const PLAYLIST_CATEGORIES: PlaylistCategoryOption[] = [
  { id: "all", label: "All" },
  { id: "pop", label: "Pop" },
  { id: "rnb", label: "R&B" },
  { id: "rap", label: "Rap & Hip-Hop" },
  { id: "africa", label: "Africa" },
  { id: "gospel", label: "Gospel" },
];
export interface Playlist {
  id: string;
  name: string;
  description: string;
  image: string; // Placeholder - will be fetched from first track or provided
  searchTerms: string[]; // Artists/songs to search for
  category: PlaylistCategory;
  /** A single artist's own catalog, not a genre mix — flagged so the UI can visually set it apart. */
  isArtist?: boolean;
}
// African music playlists with curated search terms
export const PLAYLISTS: Playlist[] = [
  {
    id: "trending-nigeria",
    category: "africa",
    name: "Trending Nigeria",
    description: "Nigeria's Top 100 right now",
    image: "",
    // Chart-driven: Apple's Most Played feed for the Nigerian storefront
    searchTerms: ["__chart:ng"],
  },
  {
    id: "global-top-100",
    category: "pop",
    name: "Global Top 100",
    description: "The world's biggest hits right now",
    image: "",
    searchTerms: ["__chart:us"],
  },
  {
    id: "afrobeats-chill",
    category: "africa",
    name: "Afrobeats & Chill",
    description: "Smooth Afrobeats vibes",
    image: "",
    searchTerms: [
      "wizkid",
      "tems",
      "burna boy",
      "rema",
      "ayra starr",
      "ckay",
      "fireboy dml",
      "joeboy",
      "omah lay",
      "davido",
      "asake",
      "bnxn",
      "kizz daniel",
      "oxlade",
      "tiwa savage",
      "yemi alade",
      "ruger",
      "adekunle gold",
      "mayorkun",
      "seyi vibez",
      "odumodublvck",
      "chike",
      "simi",
      "falz",
      "shallipopi",
      "olamide",
      "victony",
      "mohbad",
      "magixx",
      "zinoleesky",
      "lojay",
      "bella shmurda",
      "pheelz",
      "blaqbonez",
      "wande coal",
      "naira marley",
      "zlatan",
      "crayon",
      "teni",
      "niniola",
      "mr eazi",
      "wurld",
      "ladipoe",
      "johnny drille",
      "fave",
      "bloody civilian",
      "libianca",
      "young jonn",
      "bayanni",
    ],
  },
  {
    id: "amapiano-hits",
    category: "africa",
    name: "Amapiano Hits",
    description: "South African piano vibes",
    image: "",
    searchTerms: [
      "kabza de small",
      "dj maphorisa",
      "focalistic",
      "uncle waffles",
      "young stunna",
      "daliwonga",
      "tyler icu",
      "dbn gogo",
      "musa keys",
      "major league djz",
      "kelvin momo",
      "de mthuda",
      "mr jazziq",
      "lady du",
      "tyla",
      "dj stokie",
      "oscar mbo",
      "mas musiq",
      "nkosazana daughter",
      "zee nxumalo",
      "kamo mphela",
      "sir trill",
      "boohle",
      "ami faku",
      "elaine",
      "sha sha",
      "heavy k",
      "vigro deep",
      "reece madlisa",
      "zuma",
      "busta 929",
      "djy biza",
      "pcee",
      "zee nxumalo",
      "felo le tee",
      "myztro",
    ],
  },
  {
    id: "international-gospel",
    category: "gospel",
    name: "International Gospel",
    description: "Worship & praise from around the world",
    image: "",
    searchTerms: [
      // Contemporary worship
      "hillsong worship",
      "hillsong united",
      "elevation worship",
      "maverick city music",
      "bethel music",
      "chandler moore",
      "naomi raine",
      "dante bowe",
      "brandon lake",
      "cody carnes",
      "kari jobe",
      "chris tomlin",
      "phil wickham",
      "lauren daigle",
      "tauren wells",
      "for king and country",
      "mercyme",
      "casting crowns",
      "michael w smith",
      "don moen",
      "ron kenoly",
      // Gospel / urban gospel
      "kirk franklin",
      "tasha cobbs leonard",
      "cece winans",
      "donnie mcclurkin",
      "fred hammond",
      "marvin sapp",
      "yolanda adams",
      "israel houghton",
      "travis greene",
      "tye tribbett",
      "william mcdowell",
      "hezekiah walker",
      "kierra sheard",
      "mary mary",
      "the clark sisters",
      "jonathan mcreynolds",
      "todd dulaney",
    ],
  },
  {
    id: "og-gospel",
    category: "gospel",
    name: "OG Gospel",
    description: "Classic praise & worship and gospel legends",
    image: "",
    searchTerms: [
      // 90s praise & worship era (Integrity / Hosanna! Music)
      "ron kenoly",
      "alvin slaughter",
      "don moen",
      "bob fitts",
      "lenny leblanc",
      "paul wilbur",
      "terry macalmon",
      "maranatha singers",
      "hosanna music",
      "women of faith",
      "darlene zschech",
      "twila paris",
      "sandi patty",
      "steve green",
      "gaither vocal band",
      // Classic gospel legends
      "andrae crouch",
      "the winans",
      "bebe and cece winans",
      "shirley caesar",
      "mahalia jackson",
      "james cleveland",
      "walter hawkins",
      "edwin hawkins",
      "tramaine hawkins",
      "commissioned",
      "mississippi mass choir",
      "kurt carr",
      "john p kee",
      "vanessa bell armstrong",
      "dottie peoples",
      "richard smallwood",
      "helen baylor",
    ],
  },
  {
    id: "nigerian-gospel",
    category: "gospel",
    name: "Nigerian Gospel",
    description: "Praise & worship, old school to new wave",
    image: "",
    searchTerms: [
      // New wave / contemporary
      "sinach",
      "nathaniel bassey",
      "mercy chinwo",
      "moses bliss",
      "ada ehi",
      "dunsin oyekan",
      "judikay",
      "frank edwards",
      "tim godfrey",
      "__artist:1454576171",
      "steve crown",
      "prospa ochimana",
      "victoria orenze",
      "sunmisola agbebi",
      "lawrence oyor",
      "theophilus sunday",
      "minister guc",
      "chioma jesus",
      "preye odede",
      "samsong",
      "joe praize",
      "buchi",
      "limoblaze",
      "greatman takit",
      "ebuka songs",
      "neon adejo",
      "mike abdul",
      "elijah oyelade",
      "adeyinka alaseyori",
      "anendlessocean",
      // Old school / classics
      "tope alabi",
      "bola are",
      "shola allyson",
      "yinka ayefele",
      "panam percy paul",
      "agatha moses",
      "patty obasi",
      "chinedu nwadike",
      "osinachi nwachukwu",
      "sammie okposo",
      "midnight crew",
      "lara george",
      "kefee",
      "nosa",
      "ty bello",
    ],
  },
  {
    id: "naija-throwback",
    category: "africa",
    name: "Naija Throwback",
    description: "Classic Nigerian hits",
    image: "",
    searchTerms: [
      "2baba",
      "dbanj",
      "psquare",
      "timaya",
      "wande coal",
      "__artist:152359995",
      "phyno",
      "iyanya",
      "banky w",
      "9ice",
      "__artist:898937468",
      "duncan mighty",
      "tekno",
      "korede bello",
      "wizkid",
      "davido",
      "burna boy",
      "olamide",
      "dr sid",
      "naeto c",
      "mo hits",
      "styl plus",
      "dare art alade",
      "__artist:26089928",
      "seyi shay",
      "tiwa savage",
      "ice prince",
      "jesse jagz",
      "mi abaga",
      "terry g",
      "skales",
      "yung6ix",
      "oritsefemi",
      "kcee",
      "harrysong",
      "patoranking",
      "dagrin",
      "lil kesh",
      "vector tha viper",
      "__artist:452279375",
      "olu maintain",
      "sound sultan",
      "faze originality",
      "lord of ajasa",
      "don jazzy",
      "ycee",
      "omawumi",
      "lagbaja",
      "__yearrange:2004:2020",
    ],
  },
  {
    id: "nigerian-classics",
    category: "africa",
    name: "Nigerian Classics",
    description: "Old school Nigerian legends",
    image: "",
    searchTerms: [
      "fela kuti",
      "king sunny ade",
      "ebenezer obey",
      "oliver de coque",
      "seun kuti",
      "femi kuti",
      "onyeka onwenu",
      "christy essien igbokwe",
      "majek fashek",
      "sonny okosun",
      "keziah jones",
      "__yearrange::2005",
    ],
  },
  {
    id: "afro-classics",
    category: "africa",
    name: "Afro Classics",
    description: "Legendary African sounds",
    image: "",
    searchTerms: [
      "fela kuti",
      "miriam makeba",
      "youssou ndour",
      "salif keita",
      "king sunny ade",
      "ebenezer obey",
      "oliver de coque",
      "brenda fassie",
      "hugh masekela",
      "angelique kidjo",
      "manu dibango",
      "ali farka toure",
      "baaba maal",
      "ladysmith black mambazo",
      "cesaria evora",
      "tinariwen",
      "toumani diabate",
      "orchestra baobab",
      "franco luambo",
      "tabu ley rochereau",
      "papa wemba",
      "koffi olomide",
      "awilo longomba",
      "lokua kanza",
      "richard bona",
      "keziah jones",
      "seun kuti",
      "femi kuti",
      "onyeka onwenu",
      "christy essien igbokwe",
      "majek fashek",
      "sonny okosun",
      "__yearrange::2010",
    ],
  },
  {
    id: "east-africa-vibes",
    category: "africa",
    name: "East Africa Vibes",
    description: "Bongo Flava & more",
    image: "",
    searchTerms: [
      "diamond platnumz",
      "harmonize",
      "rayvanny",
      "sauti sol",
      "nyashinski",
      "zuchu",
      "ali kiba",
      "tanasha donna",
      "khaligraph jones",
      "otile brown",
      "mbosso",
      "nandy",
      "__artist:1588944195",
      "nviiri the storyteller",
      "nikita kering",
      "bensoul",
      "mejja",
      "fena gitu",
      "size 8",
      "wyre",
      "nameless",
      "jua cali",
      "bahati kenya",
      "willy paul",
      "arrow bwoy",
      "navy kenzo",
      "vanessa mdee",
      "darassa",
      "billnass",
      "marioo",
      "kusah",
      "alikiba",
      "barnaba",
      "lava lava",
      "rich mavoko",
    ],
  },
  {
    id: "ghana-sounds",
    category: "africa",
    name: "Ghana Sounds",
    description: "Hiplife & Highlife hits",
    image: "",
    searchTerms: [
      "sarkodie",
      "shatta wale",
      "stonebwoy",
      "kuami eugene",
      "king promise",
      "black sherif",
      "gyakie",
      "amaarae",
      "kidi",
      "ofori amponsah",
      "r2bees",
      "kwesi arthur",
      "camidoh",
      "darkovibes",
      "medikal",
      "joey b",
      "e.l ghana",
      "kofi kinaata",
      "becca ghana",
      "fuse odg",
      "mr eazi",
      "efya",
      "mzvee",
      "wendy shay",
      "sista afia",
      "fantana",
      "dope nation",
      "daddy lumba",
      "kojo antwi",
      "amakye dede",
      "castro",
      "vip ghana",
      "okyeame kwame",
      "obrafour",
      "reggie rockstone",
      "lord kenya",
    ],
  },
  {
    id: "us-hip-hop",
    category: "rap",
    name: "US Hip-Hop & Rap",
    description: "Top US rap hits",
    image: "",
    searchTerms: [
      "drake", "kendrick lamar", "j cole", "travis scott", "future",
      "21 savage", "lil baby", "lil wayne", "nicki minaj", "cardi b",
      "megan thee stallion", "doja cat", "post malone", "tyler the creator",
      "asap rocky", "playboi carti", "gunna", "lil uzi vert", "young thug",
      "metro boomin", "latto", "glorilla", "ice spice", "sexyy red",
      "central cee", "lil durk", "polo g", "rod wave", "nle choppa",
      "dababy", "roddy ricch", "moneybagg yo", "yeat", "ken carson",
      "destroy lonely", "kanye west", "jay z", "eminem", "50 cent",
      "nas", "lil yachty", "kodak black", "youngboy never broke again",
      "chief keef", "denzel curry", "jid", "freddie gibbs", "mac miller",
      "schoolboy q", "asap ferg",
    ],
  },
  {
    id: "uk-drill-grime",
    category: "rap",
    name: "UK Drill & Grime",
    description: "Britain's biggest rap sounds",
    image: "",
    searchTerms: [
      "stormzy", "dave", "skepta", "aj tracey", "headie one", "digga d",
      "unknown t", "fredo", "m24", "russ millions", "tion wayne",
      "bugzy malone", "giggs", "wiley", "dizzee rascal", "kano", "ghetts",
      "jme", "chip", "67", "abra cadabra", "nines", "k trap", "j hus",
      "not3s", "mist", "yxng bane", "octavian", "aitch", "pa salieu",
      "little simz", "ms banks", "ivorian doll", "shaybo", "backroad gee",
      "potter payper", "loski", "afro b",
    ],
  },
  {
    id: "us-rnb",
    category: "rnb",
    name: "US R&B",
    description: "Smooth R&B & soul",
    image: "",
    searchTerms: [
      "the weeknd", "sza", "summer walker", "brent faiyaz", "bryson tiller",
      "h.e.r.", "daniel caesar", "giveon", "khalid", "frank ocean",
      "miguel", "kehlani", "jhene aiko", "ari lennox", "jazmine sullivan",
      "victoria monet", "muni long", "chris brown", "usher", "trey songz",
      "ne-yo", "john legend", "alicia keys", "beyonce", "rihanna",
      "mariah carey", "mary j blige", "ella mai", "tinashe", "normani",
      "kali uchis", "snoh aalegra", "lucky daye", "leon thomas", "tory lanez",
      "partynextdoor", "6lack", "ty dolla sign", "ravyn lenae", "coco jones",
      "anderson paak", "syd", "lloyd", "joe rnb", "musiq soulchild",
      "tank rnb", "boyz ii men", "babyface",
    ],
  },
  {
    id: "us-pop-hits",
    category: "pop",
    name: "US Pop Hits",
    description: "Chart-topping pop",
    image: "",
    searchTerms: [
      "taylor swift", "olivia rodrigo", "billie eilish", "ariana grande",
      "dua lipa", "harry styles", "ed sheeran", "justin bieber", "bruno mars",
      "sabrina carpenter", "chappell roan", "tate mcrae", "miley cyrus",
      "selena gomez", "shawn mendes", "halsey", "camila cabello", "demi lovato",
      "katy perry", "lady gaga", "pink", "kelly clarkson", "adele", "sia",
      "charlie puth", "benson boone", "noah kahan", "teddy swims",
      "stephen sanchez", "gracie abrams", "conan gray", "lana del rey",
      "lorde", "troye sivan", "lizzo", "jonas brothers", "maroon 5",
      "imagine dragons", "onerepublic", "ava max", "bebe rexha", "anne marie",
      "rita ora", "meghan trainor", "madison beer", "jojo siwa",
    ],
  },
  {
    id: "us-throwbacks-2000s",
    category: "pop",
    name: "2000s Throwbacks",
    description: "Y2K & 2000s hits",
    image: "",
    searchTerms: [
      "beyonce", "destiny's child", "nelly", "ja rule",
      "ashanti", "missy elliott", "timbaland", "outkast", "ludacris",
      "50 cent", "young jeezy", "t.i.", "lil jon", "ying yang twins",
      "fat joe", "fabolous", "akon", "ne-yo", "chris brown",
      "usher", "alicia keys", "__artist:3849133", "bow wow",
      "omarion", "ciara", "kelly rowland", "amerie", "fergie",
      "black eyed peas", "justin timberlake", "nsync",
      "backstreet boys", "britney spears", "christina aguilera",
      "__artist:4488522", "kelly clarkson", "avril lavigne",
      "gwen stefani", "fall out boy", "panic at the disco",
      "my chemical romance", "linkin park", "blink 182", "shaggy",
      "sean paul", "nelly furtado",
      "__yearrange:2000:2009",
    ],
  },
  {
    id: "us-throwbacks-90s",
    category: "pop",
    name: "90s Throwbacks",
    description: "The decade that defined pop, R&B & hip-hop",
    image: "",
    searchTerms: [
      "michael jackson", "whitney houston", "mariah carey", "boyz ii men",
      "tlc", "spice girls", "backstreet boys", "britney spears",
      "christina aguilera", "aaliyah", "__artist:17416", "monica",
      "sisqo", "montell jordan", "__artist:14478", "dru hill", "mary j blige",
      "toni braxton", "en vogue", "salt n pepa", "2pac", "notorious big",
      "snoop dogg", "dr dre", "wu-tang clan", "lauryn hill", "fugees",
      "outkast", "coolio", "will smith", "puff daddy",
      "ace of base", "savage garden", "hanson", "alanis morissette",
      "shania twain", "celine dion", "__artist:512633", "__artist:528564", "radiohead",
      "__artist:1016512", "green day", "smashing pumpkins", "destiny's child",
      "janet jackson", "george michael", "__artist:156209",
      "__yearrange:1990:1999",
    ],
  },
  // Artist spotlights — a single artist's own catalog, not a genre mix.
  // Starting with pop & R&B; more categories to follow.
  {
    id: "artist-rihanna",
    category: "pop",
    isArtist: true,
    name: "Rihanna",
    description: "Just Rihanna — every hit",
    image: "",
    searchTerms: ["__artist:63346553"],
  },
  {
    id: "artist-adele",
    category: "pop",
    isArtist: true,
    name: "Adele",
    description: "Adele, top to bottom",
    image: "",
    searchTerms: ["__artist:262836961"],
  },
  {
    id: "artist-taylor-swift",
    category: "pop",
    isArtist: true,
    name: "Taylor Swift",
    description: "All Taylor, every era",
    image: "",
    searchTerms: ["__artist:159260351"],
  },
  {
    id: "artist-justin-bieber",
    category: "pop",
    isArtist: true,
    name: "Justin Bieber",
    description: "Bieber's biggest hits",
    image: "",
    searchTerms: ["__artist:320569549"],
  },
  {
    id: "artist-sam-smith",
    category: "pop",
    isArtist: true,
    name: "Sam Smith",
    description: "Sam Smith's biggest ballads",
    image: "",
    searchTerms: ["__artist:156488786"],
  },
  {
    id: "artist-ed-sheeran",
    category: "pop",
    isArtist: true,
    name: "Ed Sheeran",
    description: "Ed Sheeran, top to bottom",
    image: "",
    searchTerms: ["__artist:183313439"],
  },
  {
    id: "artist-beyonce",
    category: "rnb",
    isArtist: true,
    name: "Beyoncé",
    description: "Queen Bey's greatest hits",
    image: "",
    searchTerms: ["__artist:1419227"],
  },
  {
    id: "artist-chris-brown",
    category: "rnb",
    isArtist: true,
    name: "Chris Brown",
    description: "Chris Brown, wall to wall",
    image: "",
    searchTerms: ["__artist:95705522"],
  },
  {
    id: "artist-wizkid",
    category: "africa",
    isArtist: true,
    name: "Wizkid",
    description: "Just Wizkid — every hit",
    image: "",
    searchTerms: ["__artist:309335750"],
  },
  {
    id: "artist-davido",
    category: "africa",
    isArtist: true,
    name: "Davido",
    description: "Davido, top to bottom",
    image: "",
    searchTerms: ["__artist:254654363"],
  },
  {
    id: "artist-burna-boy",
    category: "africa",
    isArtist: true,
    name: "Burna Boy",
    description: "Burna Boy, wall to wall",
    image: "",
    searchTerms: ["__artist:591899010"],
  },
  {
    id: "artist-olamide",
    category: "africa",
    isArtist: true,
    name: "Olamide",
    description: "Olamide, top to bottom",
    image: "",
    searchTerms: ["__artist:389401008"],
  },
  {
    id: "artist-john-legend",
    category: "rnb",
    isArtist: true,
    name: "John Legend",
    description: "John Legend, top to bottom",
    image: "",
    searchTerms: ["__artist:16586443"],
  },
  {
    id: "artist-usher",
    category: "rnb",
    isArtist: true,
    name: "Usher",
    description: "Usher, wall to wall",
    image: "",
    searchTerms: ["__artist:15885"],
  },
  {
    id: "artist-alicia-keys",
    category: "rnb",
    isArtist: true,
    name: "Alicia Keys",
    description: "Alicia Keys, top to bottom",
    image: "",
    searchTerms: ["__artist:316069"],
  },
  {
    id: "artist-boyz-ii-men",
    category: "rnb",
    isArtist: true,
    name: "Boyz II Men",
    description: "Boyz II Men, top to bottom",
    image: "",
    searchTerms: ["__artist:256514"],
  },
  {
    id: "artist-sza",
    category: "rnb",
    isArtist: true,
    name: "SZA",
    description: "SZA, top to bottom",
    image: "",
    searchTerms: ["__artist:605800394"],
  },
  {
    id: "artist-michael-jackson",
    category: "pop",
    isArtist: true,
    name: "Michael Jackson",
    description: "The King of Pop — every hit",
    image: "",
    searchTerms: ["__artist:32940"],
  },
];
// Get a playlist by ID
export function getPlaylistById(id: string): Playlist | undefined {
  return PLAYLISTS.find((p) => p.id === id);
}
// Get all playlist IDs
export function getPlaylistIds(): string[] {
  return PLAYLISTS.map((p) => p.id);
}
