// Curated playlists for SongIQ
// Each playlist uses search terms to fetch tracks from Apple Music/iTunes

export interface Playlist {
  id: string;
  name: string;
  description: string;
  image: string; // Placeholder - will be fetched from first track or provided
  searchTerms: string[]; // Artists/songs to search for
}

// African music playlists with curated search terms
export const PLAYLISTS: Playlist[] = [
  {
    id: "afrobeats-chill",
    name: "Afrobeats & Chill",
    description: "Smooth Afrobeats vibes",
    image: "",
    searchTerms: [
      "wizkid",
      "tems",
      "burna boy",
      "rema",
      "ayra starr",
      "ckay",
      "fireboy dml",
      "joeboy",
      "omah lay",
      "davido",
      "asake",
      "bnxn",
      "kizz daniel",
      "oxlade",
      "tiwa savage",
      "yemi alade",
      "ruger",
      "adekunle gold",
      "mayorkun",
      "seyi vibez",
      "odumodublvck",
      "chike",
      "simi",
      "falz",
      "shallipopi",
      "olamide",
      "victony",
      "mohbad",
      "magixx",
      "zinoleesky",
      "lojay",
      "bella shmurda",
      "pheelz",
      "blaqbonez",
      "wande coal",
      "naira marley",
      "zlatan",
      "crayon",
      "teni",
      "niniola",
      "mr eazi",
      "wurld",
      "ladipoe",
      "johnny drille",
      "fave",
      "bloody civilian",
      "libianca",
      "young jonn",
      "bayanni",
    ],
  },
  {
    id: "amapiano-hits",
    name: "Amapiano Hits",
    description: "South African piano vibes",
    image: "",
    searchTerms: [
      "kabza de small",
      "dj maphorisa",
      "focalistic",
      "uncle waffles",
      "young stunna",
      "daliwonga",
      "tyler icu",
      "dbn gogo",
      "musa keys",
      "major league djz",
      "kelvin momo",
      "de mthuda",
      "mr jazziq",
      "lady du",
      "costa titch",
      "tyla",
      "dj stokie",
      "oscar mbo",
      "mas musiq",
      "nkosazana daughter",
      "zee nxumalo",
      "kamo mphela",
      "sir trill",
      "boohle",
      "ami faku",
      "elaine",
      "sha sha",
      "heavy k",
      "vigro deep",
      "reece madlisa",
      "zuma",
      "busta 929",
      "djy biza",
      "pcee",
      "zee nxumalo",
      "felo le tee",
      "myztro",
    ],
  },
  {
    id: "naija-throwback",
    name: "Naija Throwback",
    description: "Classic Nigerian hits",
    image: "",
    searchTerms: [
      "2baba",
      "dbanj",
      "psquare",
      "timaya",
      "wande coal",
      "flavour",
      "phyno",
      "iyanya",
      "banky w",
      "9ice",
      "bracket",
      "duncan mighty",
      "tekno",
      "korede bello",
      "wizkid superstar",
      "davido skelewu",
      "burna boy like to party",
      "olamide shakiti bobo",
      "dr sid",
      "naeto c",
      "mo hits",
      "styl plus",
      "dare art alade",
      "asa",
      "seyi shay",
      "tiwa savage kele kele",
      "ice prince",
      "jesse jagz",
      "mi abaga",
      "terry g",
      "skales",
      "yung6ix",
      "oritsefemi",
      "kcee",
      "harrysong",
      "patoranking",
    ],
  },
  {
    id: "afro-classics",
    name: "Afro Classics",
    description: "Legendary African sounds",
    image: "",
    searchTerms: [
      "fela kuti",
      "miriam makeba",
      "youssou ndour",
      "salif keita",
      "king sunny ade",
      "ebenezer obey",
      "oliver de coque",
      "brenda fassie",
      "hugh masekela",
      "angelique kidjo",
      "manu dibango",
      "ali farka toure",
      "baaba maal",
      "ladysmith black mambazo",
      "cesaria evora",
      "tinariwen",
      "toumani diabate",
      "orchestra baobab",
      "franco luambo",
      "tabu ley rochereau",
      "papa wemba",
      "koffi olomide",
      "awilo longomba",
      "lokua kanza",
      "richard bona",
      "keziah jones",
      "seun kuti",
      "femi kuti",
      "onyeka onwenu",
      "christy essien igbokwe",
      "majek fashek",
      "sonny okosun",
    ],
  },
  {
    id: "east-africa-vibes",
    name: "East Africa Vibes",
    description: "Bongo Flava & more",
    image: "",
    searchTerms: [
      "diamond platnumz",
      "harmonize",
      "rayvanny",
      "sauti sol",
      "nyashinski",
      "zuchu",
      "ali kiba",
      "tanasha donna",
      "khaligraph jones",
      "otile brown",
      "mbosso",
      "nandy",
      "bien",
      "nviiri the storyteller",
      "nikita kering",
      "bensoul",
      "mejja",
      "fena gitu",
      "size 8",
      "wyre",
      "nameless",
      "jua cali",
      "bahati kenya",
      "willy paul",
      "arrow bwoy",
      "jovial",
      "navy kenzo",
      "vanessa mdee",
      "darassa",
      "billnass",
      "marioo",
      "kusah",
      "alikiba",
      "barnaba",
      "lava lava",
      "rich mavoko",
    ],
  },
  {
    id: "ghana-sounds",
    name: "Ghana Sounds",
    description: "Hiplife & Highlife hits",
    image: "",
    searchTerms: [
      "sarkodie",
      "shatta wale",
      "stonebwoy",
      "kuami eugene",
      "king promise",
      "black sherif",
      "gyakie",
      "amaarae",
      "kidi",
      "ofori amponsah",
      "r2bees",
      "kwesi arthur",
      "camidoh",
      "darkovibes",
      "medikal",
      "joey b",
      "e.l ghana",
      "kofi kinaata",
      "becca ghana",
      "fuse odg",
      "mr eazi",
      "efya",
      "mzvee",
      "wendy shay",
      "sista afia",
      "fantana",
      "dope nation",
      "daddy lumba",
      "kojo antwi",
      "amakye dede",
      "castro",
      "vip ghana",
      "okyeame kwame",
      "obrafour",
      "reggie rockstone",
      "lord kenya",
    ],
  },
];

// Get a playlist by ID
export function getPlaylistById(id: string): Playlist | undefined {
  return PLAYLISTS.find((p) => p.id === id);
}

// Get all playlist IDs
export function getPlaylistIds(): string[] {
  return PLAYLISTS.map((p) => p.id);
}
