-- Web push reminders for the Daily Challenge.

-- VAPID keypair, generated by the cleanup cron on first run and never
-- exposed to clients (public key is served via the RPC below).
CREATE TABLE public.push_vapid (
  id INTEGER NOT NULL PRIMARY KEY DEFAULT 1 CHECK (id = 1),
  public_key TEXT NOT NULL,
  private_key TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE public.push_vapid ENABLE ROW LEVEL SECURITY;
-- No policies: service role only.

CREATE OR REPLACE FUNCTION public.get_vapid_public_key()
RETURNS text
LANGUAGE sql
STABLE
SECURITY DEFINER
SET search_path = public
AS $$
  SELECT public_key FROM push_vapid WHERE id = 1;
$$;

REVOKE ALL ON FUNCTION public.get_vapid_public_key() FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.get_vapid_public_key() TO anon, authenticated;

-- One row per browser subscription, tied to the anonymous player identity.
CREATE TABLE public.push_subscriptions (
  id UUID NOT NULL DEFAULT gen_random_uuid() PRIMARY KEY,
  player_id UUID NOT NULL,
  endpoint TEXT NOT NULL UNIQUE,
  p256dh TEXT NOT NULL,
  auth TEXT NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  last_notified DATE
);

CREATE INDEX idx_push_subscriptions_player ON public.push_subscriptions(player_id);
CREATE INDEX idx_push_subscriptions_last_notified ON public.push_subscriptions(last_notified);

ALTER TABLE public.push_subscriptions ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Players manage their own push subscriptions"
  ON public.push_subscriptions
  FOR ALL
  TO authenticated
  USING (auth.uid() = player_id)
  WITH CHECK (auth.uid() = player_id);
